
version: 1
disable_existing_loggers: false

formatters:
    precise:
        format: "[%(asctime)s] [%(name)s][%(levelname)s]  %(message)s (%(filename)s:%(lineno)d)"
    colored:
        format: "[%(asctime)s] [%(name)s][%(levelname)s]  %(message)s (%(filename)s:%(lineno)d)"
        class: qtpyvcp.lib.colored_formatter.ColoredFormatter
handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: precise
        filename: ./qtpyvcp.log
        maxBytes: 10485760
        backupCount: 10
    console:
        class: logging.StreamHandler
        formatter: colored
loggers:
    opcua:
        level: WARN
    PyQt5:
        level: DEBUG
    PyQt5.uic:
        level: WARN

root:
    level: DEBUG
    handlers: [file, console]